# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from typing import Any, List, Literal, Optional

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class FunctionHinterConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['function_hinter'] = Field(
        default='function_hinter',
        description='A component that provides a hint to the agent about which functions are available to call.\n\nContent can be truncated to token category limit: No\n\n\n### Accepts Messages\n\n*(none)*\n\n### Presentation Elements\n\n- **hint**: Lists of available functions\n',
        title='Type',
    )
    id: str = Field(
        ...,
        description='The ID of the component.  This is a unique client-assigned name used to refer to this component in other parts of the agent configuration.',
        title='Id',
    )
    token_category: Optional[str] = Field(
        default=None,
        description='The token category from presentation_config.token_limits that presentation elements from this component count against.',
        title='Token Category',
    )
    message_channels: Optional[List[str]] = Field(
        default=[],
        description='The channels on which to listen for messages.',
        title='Message Channels',
    )
    transient: Optional[bool] = Field(
        default=False,
        description='If True, the component is transient and does not persist state between API requests.  This means that it will only present data sent within a call to a generate-* endpoint; messages posted directly to the agent will be immediately dropped.',
        title='Transient',
    )
    prefix: Optional[str] = Field(
        default='You must call one of these functions:',
        description='A prefix for the function hint when presented to the agent.',
        title='Prefix',
    )


class KVStoreConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['kv_store'] = Field(
        default='kv_store',
        description='A key-value store component that supports hierarchical keys.  When hierarchical keys are used, non-leaf keys may have a value in addition to having sub-keys.  Setting a value to null will delete the value. If the key has no value and no subkeys, it will be deleted. If the parent key no longer has a value or any sub-keys, the parent will also be deleted.\n\nContent can be truncated to token category limit: No\n\n\n### Accepts Messages\n\n- KVMessage\n\n### Presentation Elements\n\n- **data**: The stored key-value pairs\n',
        title='Type',
    )
    id: str = Field(
        ...,
        description='The ID of the component.  This is a unique client-assigned name used to refer to this component in other parts of the agent configuration.',
        title='Id',
    )
    token_category: Optional[str] = Field(
        default=None,
        description='The token category from presentation_config.token_limits that presentation elements from this component count against.',
        title='Token Category',
    )
    message_channels: Optional[List[str]] = Field(
        default=[],
        description='The channels on which to listen for messages.',
        title='Message Channels',
    )
    transient: Optional[bool] = Field(
        default=False,
        description='If True, the component is transient and does not persist state between API requests.  This means that it will only present data sent within a call to a generate-* endpoint; messages posted directly to the agent will be immediately dropped.',
        title='Transient',
    )
    delimiter: Optional[str] = Field(
        default=None,
        description="An optional delimiter to separate hierarchy level names in compound keys. Often a single character (e.g. '.', '/'), but may be any string (e.g. '::', '->'). If set, the store will be a hierarchical key-value store with a nested-mapping structure. If not set, the store will be a flat key-value store without any key splitting. Note that setting the value of an intermediate hierarchy level in a hierarchical store to None will deleted the entire hierarchy level.  E.g. Setting 'a.b' to None will delete 'a.b.c' and 'a.b.d'.  A flat store only operates on full keys.",
        title='Delimiter',
    )
    description: Optional[str] = Field(
        default=None,
        description='A description of the items in the store that will appear before the store content.',
        title='Description',
    )
    indent: Optional[str] = Field(
        default='  ',
        description='The string to use for indentation when presenting hierarchical data.',
        title='Indent',
    )


class LimitedListConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['limited_list'] = Field(
        default='limited_list',
        description='A list that stores a limited number of items.\n\nContent can be truncated to token category limit: Yes\n\n\n### Accepts Messages\n\n- ContentMessage\n\n### Presentation Elements\n\n- **items**: The stored items, undecorated\n- **itemized**: The stored items, as a bulleted list\n',
        title='Type',
    )
    id: str = Field(
        ...,
        description='The ID of the component.  This is a unique client-assigned name used to refer to this component in other parts of the agent configuration.',
        title='Id',
    )
    token_category: Optional[str] = Field(
        default=None,
        description='The token category from presentation_config.token_limits that presentation elements from this component count against.',
        title='Token Category',
    )
    message_channels: Optional[List[str]] = Field(
        default=[],
        description='The channels on which to listen for messages.',
        title='Message Channels',
    )
    transient: Optional[bool] = Field(
        default=False,
        description='If True, the component is transient and does not persist state between API requests.  This means that it will only present data sent within a call to a generate-* endpoint; messages posted directly to the agent will be immediately dropped.',
        title='Transient',
    )
    max_entries: Optional[int] = Field(
        default=1000,
        description='The maximum number of items to store in the list.  If the list exceeds this size, the oldest items will be removed.  Note that the oldest items may not be presented to the LLM if this would exceed the LLM context size or the presentation_config.token_limit for the category assigned to this component.',
        gt=0,
        title='Max Entries',
    )
    description: Optional[str] = Field(
        default=None,
        description='A description of what this list contains that will appear before the list content in both plain and itemized forms.',
        title='Description',
    )
    accept_generation: Optional[bool] = Field(
        default=True,
        description="If True, the agent's response to generation requests will be appended to the list.",
        title='Accept Generation',
    )


class PuppeteerKVStoreConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['puppeteer_kv_store'] = Field(
        default='puppeteer_kv_store',
        description='An (optionally) hierarchical key-value store designed for a puppeteer agent that merges identical key-value pairs across puppets. All entries are tagged with the puppet_id of the associated puppet(s).Non-leaf keys may have values for puppets in addition to having sub-keys.  Setting a key to null for a puppet will remove that puppet from all values at that key.  If no puppets have values at this key and there are no subkeys below this key, the key will be removed. If the parent key has no puppet vales and no subkeys, it will also be removed.\n\nContent can be truncated to token category limit: No\n\n\n### Accepts Messages\n\n- PuppeteerMessage (only KVMessage entries)\n\n### Presentation Elements\n\n- **merged**: The store content.\n',
        title='Type',
    )
    id: str = Field(
        ...,
        description='The ID of the component.  This is a unique client-assigned name used to refer to this component in other parts of the agent configuration.',
        title='Id',
    )
    token_category: Optional[str] = Field(
        default=None,
        description='The token category from presentation_config.token_limits that presentation elements from this component count against.',
        title='Token Category',
    )
    message_channels: Optional[List[str]] = Field(
        default=[],
        description='The channels on which to listen for messages.',
        title='Message Channels',
    )
    transient: Optional[bool] = Field(
        default=False,
        description='If True, the component is transient and does not persist state between API requests.  This means that it will only present data sent within a call to a generate-* endpoint; messages posted directly to the agent will be immediately dropped.',
        title='Transient',
    )
    description: Optional[str] = Field(
        default=None,
        description='A description of what this kv-store represents, that will appearbefore the store content.',
        title='Description',
    )
    delimiter: Optional[str] = Field(
        default=None,
        description="An optional delimiter to separate hierarchy level names in compound keys. Often a single character (e.g. '.', '/'), but may be any string (e.g. '::', '->'). If set, the store will be a hierarchical key-value store with a nested-mapping structure. If not set, the store will be a flat key-value store without any key splitting. Note that setting the value of an intermediate hierarchy level to None for a puppet will remove that puppet from all sub-keys below that level (without impacting other puppets). E.g. Setting 'a.b' to None for puppet-1 will remove puppet-1 from any values for 'a.b.c' and 'a.b.d', but leave those values associated with other puppets.  If all puppets are removed from a value, the entire value is removed.  A flat store only operates on full keys.",
        title='Delimiter',
    )
    indent: Optional[str] = Field(
        default='  ',
        description='The string to use for indentation when presenting hierarchical data.',
        title='Indent',
    )


class PuppeteerLimitedListConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['puppeteer_limited_list'] = Field(
        default='puppeteer_limited_list',
        description='A list designed for a puppeteer agent that stores a limited number ofentries, but merges identical content in the same request for different puppets into a single entry.  All entries are tagged with the puppet_id of the associated puppet(s). No ordering is guaranteed between content entries received as part of the same request.\n\nContent can be truncated to token category limit: Yes\n\n\n### Accepts Messages\n\n- PuppeteerMessage (only ContentMessage entries)\n\n### Presentation Elements\n\n- **merged**: The stored items, undecorated\n- **itemized_merged**: The stored items, as a bulleted list\n',
        title='Type',
    )
    id: str = Field(
        ...,
        description='The ID of the component.  This is a unique client-assigned name used to refer to this component in other parts of the agent configuration.',
        title='Id',
    )
    token_category: Optional[str] = Field(
        default=None,
        description='The token category from presentation_config.token_limits that presentation elements from this component count against.',
        title='Token Category',
    )
    message_channels: Optional[List[str]] = Field(
        default=[],
        description='The channels on which to listen for messages.',
        title='Message Channels',
    )
    transient: Optional[bool] = Field(
        default=False,
        description='If True, the component is transient and does not persist state between API requests.  This means that it will only present data sent within a call to a generate-* endpoint; messages posted directly to the agent will be immediately dropped.',
        title='Transient',
    )
    max_entries: Optional[int] = Field(
        default=1000,
        description='The maximum number of items to store in the list.  If the list exceeds this size, the oldest items will be removed.  Note that the oldest items may not be presented to the LLM if this would exceed the LLM context size or the presentation_config.token_limit for the category assigned to this component. If when identical entries are merged between puppets, this counts as a single entry.',
        gt=0,
        title='Max Entries',
    )
    description: Optional[str] = Field(
        default=None,
        description='A description of what this list contains that will appear before the list content in both merged and itemized_merged forms.',
        title='Description',
    )
    accept_generation: Optional[bool] = Field(
        default=False,
        description="If True, the agent's response to generation requests will be appended to the list.",
        title='Accept Generation',
    )


class StaticTextConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['static_text'] = Field(
        default='static_text',
        description='A component that presents static text to the agent.\n\nContent can be truncated to token category limit: No\n\n\n### Accepts Messages\n\n*(none)*\n\n### Presentation Elements\n\n- **text**: The stored text\n',
        title='Type',
    )
    id: str = Field(
        ...,
        description='The ID of the component.  This is a unique client-assigned name used to refer to this component in other parts of the agent configuration.',
        title='Id',
    )
    token_category: Optional[str] = Field(
        default=None,
        description='The token category from presentation_config.token_limits that presentation elements from this component count against.',
        title='Token Category',
    )
    message_channels: Optional[List[str]] = Field(
        default=[],
        description='The channels on which to listen for messages.',
        title='Message Channels',
    )
    transient: Optional[bool] = Field(
        default=False,
        description='If True, the component is transient and does not persist state between API requests.  This means that it will only present data sent within a call to a generate-* endpoint; messages posted directly to the agent will be immediately dropped.',
        title='Transient',
    )
    text: str = Field(
        ...,
        description='The text to present to the agent.  This text cannot be changed.',
        title='Text',
    )


class TextBlockConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: Literal['text_block'] = Field(
        default='text_block',
        description='A component that presents stored text to the agent until a message changes the text.  Set transient=True to not store the text between requests.\n\nContent can be truncated to token category limit: No\n\n\n### Accepts Messages\n\n- ContentMessage\n\n### Presentation Elements\n\n- **text**: The stored text\n',
        title='Type',
    )
    id: str = Field(
        ...,
        description='The ID of the component.  This is a unique client-assigned name used to refer to this component in other parts of the agent configuration.',
        title='Id',
    )
    token_category: Optional[str] = Field(
        default=None,
        description='The token category from presentation_config.token_limits that presentation elements from this component count against.',
        title='Token Category',
    )
    message_channels: Optional[List[str]] = Field(
        default=[],
        description='The channels on which to listen for messages.',
        title='Message Channels',
    )
    transient: Optional[bool] = Field(
        default=False,
        description='If True, the component is transient and does not persist state between API requests.  This means that it will only present data sent within a call to a generate-* endpoint; messages posted directly to the agent will be immediately dropped.',
        title='Transient',
    )
