# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class APIErrorType(Enum):
    server_error = 'server_error'
    invalid_generation = 'invalid_generation'
    invalid_api_key = 'invalid_api_key'
    invalid_session = 'invalid_session'
    invalid_project = 'invalid_project'
    invalid_request = 'invalid_request'
    not_found = 'not_found'
    request_limit_exceeded = 'request_limit_exceeded'
    not_ready = 'not_ready'


class ErrorDetails(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: APIErrorType
    message: str = Field(
        ..., description='A human-readable error message.', title='Message'
    )
    trace: str = Field(..., title='Trace')


class ErrorResponseModel(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    error: ErrorDetails
