# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class ValueType(Enum):
    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    null = 'null'


class SimpleParameter(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value_type: Literal['boolean', 'integer', 'null', 'number', 'string'] = Field(
        ..., title='Value Type'
    )
    docs: Optional[str] = Field(..., title='Docs')
    enumeration: Optional[List] = Field(default=None, title='Enumeration')


class ArrayParameter(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value_type: Literal['array'] = Field(default='array', title='Value Type')
    docs: Optional[str] = Field(..., title='Docs')
    items: Union[SimpleParameter, ArrayParameter, ObjectParameter] = Field(
        ..., discriminator='value_type', title='Items'
    )


class FunctionDescription(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str = Field(
        ..., max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$', title='Name'
    )
    docs: str = Field(..., max_length=1024, title='Docs')
    parameters: Dict[str, Union[SimpleParameter, ArrayParameter, ObjectParameter]] = (
        Field(..., title='Parameters')
    )
    required: List[str] = Field(..., title='Required')


class ObjectParameter(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    value_type: Literal['object'] = Field(default='object', title='Value Type')
    docs: Optional[str] = Field(..., title='Docs')
    properties: Dict[str, Union[SimpleParameter, ArrayParameter, ObjectParameter]] = (
        Field(..., title='Properties')
    )
    required: List[str] = Field(..., title='Required')


ArrayParameter.model_rebuild()
FunctionDescription.model_rebuild()
