# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from typing import Any, Dict, List, Literal

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class Resource(GeneratedModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class Service(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    service_name: str = Field(
        ..., description='Name of the service', title='Service Name'
    )
    base_type: str = Field(
        ...,
        description="Base type of the service, e.g. 'artificial-agency/torque-pocket'",
        title='Base Type',
    )
    service_category: str = Field(
        ..., description="Service category type, e.g. 'llm'", title='Service Category'
    )
    description: str = Field(
        ..., description='Description of the service', title='Description'
    )
    fixed_params: Dict[str, Any] = Field(
        ...,
        description='Fixed parameters for the service, as set in the dashboard.',
        title='Fixed Params',
    )
    client_params: Dict[str, Dict[str, Any]] = Field(
        ..., description='Parameters for the service', title='Client Params'
    )


class ListResponse(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list'] = Field(default='list', title='Object')
    has_more: bool = Field(..., title='Has More')
    data: List[Resource] = Field(..., title='Data')
