# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from enum import Enum
from typing import Any, List, Literal, Optional, Union

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class KVDelTreeMessage(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message_type: Literal['KVDelTreeMessage'] = Field(
        ...,
        description='The type of message',
        examples=['ContentMessage', 'KVMessage'],
        title='Message Type',
    )
    channels: Optional[List[str]] = Field(
        default=None, examples=[['combat'], ['']], title='Channels'
    )
    ignorable: Optional[bool] = Field(
        default=False,
        description='When False, a request that includes this message will be considered invalid if no components accept the message. When True, the message will be silently dropped if no component accepts it.',
        title='Ignorable',
    )
    key: str = Field(
        ...,
        description='The root key to delete. Any value at this key and any subkeys will be removed.  This message will only remove a single key in KV stores that are not configured to use hierarchical keys.',
        examples=['character.status_effects'],
        title='Key',
    )


class KVMessage(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message_type: Literal['KVMessage'] = Field(
        default='KVMessage', title='Message Type'
    )
    channels: Optional[List[str]] = Field(
        default=None, examples=[['attributes'], ['']], title='Channels'
    )
    ignorable: Optional[bool] = Field(
        default=False,
        description='When False, a request that includes this message will be considered invalid if no components accept the message. When True, the message will be silently dropped if no component accepts it.',
        title='Ignorable',
    )
    key: str = Field(
        ...,
        description='The key of the key-value pair.',
        examples=['health', 'inventory'],
        title='Key',
    )
    value: Optional[Union[str, List[str]]] = Field(
        ...,
        description='The value of the key-value pair.  Setting the value to null will remove the key from the key-value store.',
        examples=['5', ['candle x3', 'goblet']],
        title='Value',
    )


class Type(Enum):
    failure = 'failure'
    warning = 'warning'
    success = 'success'
    update = 'update'


class FunctionCall(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str = Field(
        ..., description='The ID of a generate_function response.', title='Id'
    )
    type: Type = Field(
        ...,
        description='The client-side outcome of attempting to execute the generated function.',
    )


class ContentMessage(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message_type: Literal['ContentMessage'] = Field(
        default='ContentMessage', title='Message Type'
    )
    channels: Optional[List[str]] = Field(
        default=None, examples=[[], []], title='Channels'
    )
    ignorable: Optional[bool] = Field(
        default=False,
        description='When False, a request that includes this message will be considered invalid if no components accept the message. When True, the message will be silently dropped if no component accepts it.',
        title='Ignorable',
    )
    content: str = Field(
        ...,
        description='An arbitrary string of content.',
        examples=[
            'You joined the server 0.7 seconds ago. Current UTC time in the real-world is: 07:05:10',
            'New perceptions: Apple at at (-1, -60, 1)',
        ],
        title='Content',
    )
    function_call: Optional[FunctionCall] = Field(
        default=None,
        description='Details linking the content in this message to a previously-generated function.',
    )


class PuppeteerMessage(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    message_type: Literal['PuppeteerMessage'] = Field(
        default='PuppeteerMessage', title='Message Type'
    )
    channels: Optional[List[str]] = Field(
        default=None, examples=[['combat'], ['']], title='Channels'
    )
    ignorable: Optional[bool] = Field(
        default=False,
        description='When False, a request that includes this message will be considered invalid if no components accept the message. When True, the message will be silently dropped if no component accepts it.',
        title='Ignorable',
    )
    puppet_id: str = Field(
        ...,
        description='The ID of the puppet.',
        examples=['lisa_135'],
        title='Puppet Id',
    )
    contents: List[Union[ContentMessage, KVMessage, KVDelTreeMessage]] = Field(
        ...,
        description='Messages related to this puppet.',
        examples=[
            [
                {'content': 'The goblin stabs you.', 'message_type': 'ContentMessage'},
                {
                    'key': 'status.effect',
                    'message_type': 'KVMessage',
                    'value': 'bleeding',
                },
                {'content': 'You take 3 damage.', 'message_type': 'ContentMessage'},
                {'key': 'status.health', 'message_type': 'KVMessage', 'value': '5'},
            ]
        ],
        title='Contents',
    )
