# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from typing import Any, Optional

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class RoleConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    core: str = Field(
        ...,
        description='The core operating instructions for an agent, describing how to call functions and boundaries on acceptable content. This should not be game-specific or character-specific.',
        title='Core',
    )
    characterization: str = Field(
        ...,
        description="Game-specific and role-specific instructions for the agent. This can include information about the game world and the agent's role in it.",
        title='Characterization',
    )
    max_size: Optional[int] = Field(
        default=0,
        description='The maximum size, in characters, for the combination of core and characterization.  If 0, there is no limit.',
        ge=0,
        title='Max Size',
    )
