# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class ServiceConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    service_name: str = Field(
        ...,
        description='The name assigned to a type of service in the Artificial Agency dashboard.',
        title='Service Name',
    )
    id: str = Field(
        ...,
        description='The ID of the service.  This is a unique client-assigned name used to refer to this service in other parts of the agent configuration.',
        title='Id',
    )
