# code generated by src/bagel/scripts/dump_client_models.py - do not edit manually.

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import ConfigDict, Field, RootModel

from artificial_agency._types import GeneratedModel


class Model(RootModel[Any]):
    root: Any


class UIConfig(GeneratedModel):
    model_config = ConfigDict(
        extra='allow',
    )
    friendly_name: Optional[str] = Field(
        default=None,
        description='A friendly name for the agent.',
        title='Friendly Name',
    )
    emoji: Optional[str] = Field(
        default=None,
        description='Either an emoji shortcode or a literal emoji to identify the agent.\nWhen specified as a shortcode, must be a valid emoji shortcode, including the wrapping \':\'s. For example: \n```\n  "emoji": ":ninja:"\n```\n\nWhen specified as a literal emoji, must be a Unicode sequence representing a single emoji. For example, in UTF-8 the JSON representation of the "ninja" emoji would be:\n```\n  "emoji": "\\ud83e\\udd77"\n```\n\nThe JSON representation of the Bulgarian flag would be:\n```\n  "emoji": "\\ud83c\\udde7\\ud83c\\uddec"\n```\n\n',
        title='Emoji',
    )
    metadata: Optional[Dict[str, str]] = Field(
        default={},
        description='Set of key-value pairs to be attached to the new agent. This can be useful for storing additional information about the agent in a structured format.  The agent has no knowledge of this information.',
        title='Metadata',
    )
